name: Deploy Development
run-name: ${{ github.actor }} is deploying development
on: [push]
jobs:
  deploy-development:
    runs-on: ubuntu-latest
    env:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      ID_TOKEN: ${{ secrets.ID_TOKEN }}
      REMOTE_BRANCH: main

    steps:
      - name: checkout repo
        uses: actions/checkout@v2

      - name: Install Google Clasp
        id: install-google-clasp
        run: sudo npm install -g @google/clasp

      - name: Write .clasprc.json file
        id: write-clasprc
        env:
          CLASPRC_JSON: ${{ secrets.CLASPRC_JSON }}
        run: echo "$CLASPRC_JSON" > ~/.clasprc.json

      - name: Login Google Clasp
        id: login-google-clasp
        run: |
          clasp login  --status      
      
      - name: Create new environment
        id: create-new-environment
        run: |
          clasp create --type sheets --rootDir ./src --title "table-Development" > ./table-development.txt && cat ./table-development.txt && cat ./.clasp.json

      - name: Push code to Google Apps Script
        id: push-code-to-google-apps-script
        run: |
          ls && clasp push